## **Atelier Pandas**

In [ ]:
# Import des bibliothèques nécessaires pour tout le notebook
import pandas as pd
import numpy as np

# On fi
# xe une graine aléatoire globale pour la reproductibilité de l'ensemble du notebook
np.random.seed(42)

print("Pandas version :", pd.__version__)
print("NumPy version  :", np.__version__)

Pandas version : 3.0.5
NumPy version  : 2.5.2

## Partie 1 – Series

1) Création d'une Series contenant 4 températures

In [9]:
# Une Series contenant 4 températures 
temperatures = pd.Series([24.5, 25.1, 26.3, 27.0])
print(temperatures)

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

2) Affichage de l'index

In [10]:
# L'Index
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

3) Affiche la 1ère valeur

In [14]:
# 1er valeur
print(temperatures.iloc[0])

24.5

4) Affiche la dernière valeur

In [15]:
# derniere valeur
print(temperatures.iloc[-1])

27.0

5) Création, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h

In [16]:
# 1 façon : passer directement le paramètre index à la création
temperatures_horaires_v1 = pd.Series(
    [24.5, 25.1, 26.3, 27.0],
    index=["12h", "13h", "14h", "15h"]
)
print("Version 1 (paramètre index) :")
print(temperatures_horaires_v1)

Version 1 (paramètre index) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [17]:
# 2 façon : passer un dictionnaire, dont les clés deviennent l'index
temperatures_horaires_v2 = pd.Series(
    {"12h": 24.5, "13h": 25.1, "14h": 26.3, "15h": 27.0}
)
print("Version 2 (dictionnaire) :")
print(temperatures_horaires_v2)

Version 2 (dictionnaire) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

6) Affiche la 1ère et la dernière valeur

In [19]:
# La 1er et la dernière valeur
print("La premiere valeur est :", temperatures_horaires_v1.iloc[0], 
      "\n la dernier valeur est :", temperatures_horaires_v1.iloc[-1])

La premiere valeur est : 24.5
 la dernier valeur est : 27.0

## Partie 2 – DataFrame

1) Création et affichage du dataframe df_test à partir du dictionnaire suivant 
- data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
}

In [21]:
# dictionnaire
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

# dataframe df_test
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [22]:
# importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

3) Affichage des dimensions de df

In [23]:
# Les dimensions df
print("Dimensions de df (lignes, colonnes) :", df.shape)

Dimensions de df (lignes, colonnes) : (605, 9)

## Partie 3 – Exploration

1) Affichage des premières lignes

In [24]:
# Les 1 lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2) Affichage des 10 premières lignes

In [25]:
# les 10 premières lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3) Affichage des dernières lignes

In [26]:
# Les dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4) Affiche le nombre de lignes

In [31]:
# Nombre de lignes
print("nombre de ligne est :", df.shape[0])

nombre de ligne est : 605

5) Affiche le nombre de colonnes

In [34]:
# Nombre de colonnes 
print("nombre de colonne est :", df.shape[1])

nombre de colonne est : 9

6) Affiche les noms des colonnes

In [35]:
# noms des colonnes
print(df.columns.tolist())

['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

7) Affiche les informations générales

In [36]:
# Les informations generales
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

8) Affiche les statistiques descriptives

In [38]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection

1) Sélection de la colonne "temperature"

In [39]:
# Selection de la colonne tmp
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

2) Sélection des colonnes "temperature", "humidite", "pression" et "consommation"

In [40]:
# Sélection des colonnes "temperature", "humidite", "pression" et "consommation"  
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

3) Sélection des 5 premières lignes avec loc

In [41]:
# les 5 premieres lignes 
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

4) Sélection des 5 premières lignes et les 4 premières colonnes avec iloc

In [42]:
# les 5 premieres lignes et les 4 premiere colonnes
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes

1) Ajoute de la colonne "temperature_fahrenheit"

In [43]:
# ajoute de la colonne
df["temperature_fahrenheit"] = df["temperature"] * 9 / 5 + 32
df[["temperature", "temperature_fahrenheit"]].head()

   temperature  temperature_fahrenheit
0        25.46                  77.828
1        24.00                  75.200
2        25.82                  78.476
3        28.23                  82.814
4        20.58                  69.044

2) Ajoutons la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" 
- (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [44]:
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df[["temperature", "niveau_temperature"]].head()

   temperature niveau_temperature
0        25.46            Normale
1        24.00            Normale
2        25.82            Normale
3        28.23            Normale
4        20.58            Normale

In [45]:
df["niveau_temperature"].value_counts()

niveau_temperature
Normale    559
Élevée      46
Name: count, dtype: int64

3) Renommage de la colonne "humidite" en "humidite_relative"

In [47]:
# renommage de la colonne 
df = df.rename(columns={"humidite": "humidite_relative"})
df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite_relative',
 'pression',
 'consommation',
 'etat',
 'temperature_fahrenheit',
 'niveau_temperature']

4) Supprime de la colonne "temperature_fahrenheit"

In [48]:
# colonne supprimer et nouveau visualisation
df = df.drop(columns=["temperature_fahrenheit"])
df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite_relative',
 'pression',
 'consommation',
 'etat',
 'niveau_temperature']

## Partie 6 – Filtrage

1) Récupération uniquement les lignes telles que température > 30

In [49]:
# les lignes sont recuperer si tmp > 30
df_temp_elevee = df[df["temperature"] > 30]
print("Nombre de lignes :", df_temp_elevee.shape[0])
df_temp_elevee.head()

Nombre de lignes : 46

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Élevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Élevée

2) Récupération uniquement les lignes telles température > 30 et humidité > 70

In [50]:
# les lignes telles température > 30 et humidité > 70 
df_temp_hum_elevee = df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]
print("Nombre de lignes :", df_temp_hum_elevee.shape[0])
df_temp_hum_elevee.head()

Nombre de lignes : 14

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

## Partie 7 : Tri

1) Création df_trie1 pour trier en fonction de la température croissante

In [51]:
#  df_trie1 pour trier en fonction de la température croissante
df_trie1 = df.sort_values(by="temperature", ascending=True)
df_trie1.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 06:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 06:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 06:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 01:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale

2) Création df_trie2 pour trier en fonction de la température décroissante

In [52]:
# df_trie2 pour trier en fonction de la température décroissante
df_trie2 = df.sort_values(by="temperature", ascending=False)
df_trie2.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

3) Création top10 pour voir les 10 températures les plus élevées

In [53]:
# top10 pour voir les 10 températures les plus élevées 
top10 = df.nlargest(10, "temperature")
top10[["id_mesure", "batiment", "temperature"]]

    id_mesure batiment  temperature
502     M0048     B004        58.70
43      M0575     B004        34.72
129     M0592     B002        33.60
211     M0370     B004        33.29
165     M0323     B004        33.01
118     M0365     B002        32.90
520     M0063     B001        32.72
438     M0558     B002        32.56
47      M0082     B004        32.46
169     M0546     B002        32.36

4) Trie en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

In [54]:
df_trie_multi = df.sort_values(by=["batiment", "temperature"], ascending=[True, False])
df_trie_multi.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale
467,M0241,2026-01-15 00:00:00,C001,B001,28.85,66.31,1004.98,175.06,OK,Normale
567,M0591,2026-01-29 14:00:00,C003,B001,28.71,55.02,1010.18,201.62,OK,Normale
85,M0074,2026-01-08 01:00:00,C002,B001,28.41,39.33,1011.11,187.94,OK,Normale
293,M0230,2026-01-14 13:00:00,C002,B001,28.31,70.29,1023.91,95.36,OK,Normale
263,M0579,2026-01-29 02:00:00,C003,B001,28.11,65.56,1016.97,196.48,OK,Normale

## Partie 8 : Analyse

1) Affiche la consommation moyenne par bâtiment

In [55]:
# la consommation moyenne par bâtiment 
conso_moyenne_par_batiment = df.groupby("batiment")["consommation"].mean()
conso_moyenne_par_batiment

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

2) Affiche le minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment

In [56]:
# e minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment
stats_temp_par_batiment = df.groupby("batiment")["temperature"].agg(["min", "max", "mean", "std"])
stats_temp_par_batiment

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

3) Affichage, par bâtiment, le maximum et la moyenne de la température et de la consommation

In [57]:
stats_par_batiment = df.groupby("batiment").agg({
    "temperature": ["max", "mean"],
    "consommation": ["max", "mean"]
})
stats_par_batiment

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

4) Affichage de la température moyenne globale

In [58]:
print("Température moyenne globale :", round(df["temperature"].mean(), 2))

Température moyenne globale : 24.88

5) Affiche la température maximale

In [59]:
print("Température maximale :", df["temperature"].max())

Température maximale : 58.7

6) Affiche la consommation totale

In [60]:
print("Consommation totale :", round(df["consommation"].sum(), 2))

Consommation totale : 125205.25

7) Le bâtiment consomme le plus en moyenne ?

In [61]:
batiment_plus_energivore = conso_moyenne_par_batiment.idxmax()
print("Bâtiment consommant le plus en moyenne :", batiment_plus_energivore)
print("Consommation moyenne associée :", round(conso_moyenne_par_batiment.max(), 2))

Bâtiment consommant le plus en moyenne : B004
Consommation moyenne associée : 282.55

8) Affiche le nombre d'alertes par bâtiment

In [62]:
alertes_par_batiment = df[df["etat"] == "ALERTE"].groupby("batiment").size()
alertes_par_batiment

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

## Partie 9 : Gestion des valeurs manquantes

1) Affiche le nombre de valeurs manquantes par colonne

In [63]:
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

2) Affiche le nombre total des valeurs manquantes

In [64]:
print("Total des valeurs manquantes :", df.isna().sum().sum())

Total des valeurs manquantes : 25

3) Affiche le taux de valeurs manquantes

In [65]:
taux_manquantes = df.isna().sum().sum() / df.size * 100
print(f"Taux de valeurs manquantes : {taux_manquantes:.2f} %")

Taux de valeurs manquantes : 0.41 %

4) Affiche les lignes contenant des valeurs manquantes

In [66]:
lignes_manquantes = df[df.isna().any(axis=1)]
print("Nombre de lignes concernées :", lignes_manquantes.shape[0])
lignes_manquantes

Nombre de lignes concernées : 25

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

5) Pour la température et l’humidité, remplacement les valeurs manquantes par les moyennes

In [67]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"] = df["humidite_relative"].fillna(df["humidite_relative"].mean())
df[["temperature", "humidite_relative"]].isna().sum()

temperature          0
humidite_relative    0
dtype: int64

6) Pour la consommation, remplacement des valeurs manquantes par la médiane

In [68]:
df["consommation"] = df["consommation"].fillna(df["consommation"].median())
df["consommation"].isna().sum()

np.int64(0)

7) Pour "etat", remplacement des valeurs manquantes par "INCONNU"

In [70]:
df["etat"] = df["etat"].fillna("INCONNU")
df["etat"].value_counts()

etat
OK         567
ALERTE      29
ERREUR       5
INCONNU      4
Name: count, dtype: int64

In [71]:
# verification 
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          0
etat                  0
niveau_temperature    0
dtype: int64

## Partie 10 : Gestion des doublons

1) Affiche le nombre de doublons

In [72]:
print("Nombre de doublons :", df.duplicated().sum())

Nombre de doublons : 5

2) Affiche des doublons

In [73]:
df[df.duplicated()]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
183,M0599,2026-01-29 22:00:00,C011,B004,22.02,68.09,1005.90,227.81,OK,Normale
231,M0026,2026-01-06 01:00:00,C002,B001,22.87,77.99,1010.15,213.19,OK,Normale
355,M0147,2026-01-11 02:00:00,C003,B001,26.14,84.97,1003.59,142.31,OK,Normale
538,M0456,2026-01-23 23:00:00,C012,B004,20.68,72.69,1022.77,309.01,OK,Normale
539,M0302,2026-01-17 13:00:00,C002,B001,22.05,58.26,1007.30,140.42,OK,Normale

3) Supprimons les doublons puis vérifier la suppression

In [74]:
df = df.drop_duplicates()
print("Nombre de doublons après suppression :", df.duplicated().sum())
print("Nouvelles dimensions de df :", df.shape)

Nombre de doublons après suppression : 0
Nouvelles dimensions de df : (600, 10)

## Partie 11 : Statistiques descriptives

1) Pour la température, affiche le minimum, le maximum, la moyenne, la mediane, l’écart-type et 
le nombre de valeurs

In [75]:
stats_temperature = {
    "min": df["temperature"].min(),
    "max": df["temperature"].max(),
    "mean": df["temperature"].mean(),
    "median": df["temperature"].median(),
    "std": df["temperature"].std(),
    "count": df["temperature"].count()
}
pd.Series(stats_temperature)

min       -18.500000
max        58.700000
mean       24.896033
median     24.878314
std         4.048027
count     600.000000
dtype: float64

2) Pour "etat", affiche le mode et le nombre de mesures par état (OK, ALERTE, ERREUR)

In [76]:
print("Mode de la colonne 'etat' :", df["etat"].mode()[0])
print()
print(df["etat"].value_counts())

Mode de la colonne 'etat' : OK

etat
OK         562
ALERTE      29
ERREUR       5
INCONNU      4
Name: count, dtype: int64

## Partie 12 : Exportation

1) Exportation du dataframe nettoyé dans exports/donnees_nettoyees.csv

In [77]:
df.to_csv("../exports/donnees_nettoyees.csv", index=False)
print("Export CSV terminé.")

Export CSV terminé.

2) Exportation du dataframe nettoyé dans exports/donnees_nettoyees.json

In [79]:
df.to_json("../exports/donnees_nettoyees.json", orient="records", indent=2, force_ascii=False)
print("Export JSON terminé.")

Export JSON terminé.