## **Atelier Pandas**

In [ ]:
# Import des bibliothèques nécessaires pour tout le notebook
import pandas as pd
import numpy as np

# On fi
# xe une graine aléatoire globale pour la reproductibilité de l'ensemble du notebook
np.random.seed(42)

print("Pandas version :", pd.__version__)
print("NumPy version  :", np.__version__)

Pandas version : 3.0.5
NumPy version  : 2.5.2

## Partie 1 – Series

1) Création d'une Series contenant 4 températures

In [9]:
# Une Series contenant 4 températures 
temperatures = pd.Series([24.5, 25.1, 26.3, 27.0])
print(temperatures)

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

2) Affichage de l'index

In [10]:
# L'Index
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

3) Affiche la 1ère valeur

In [14]:
# 1er valeur
print(temperatures.iloc[0])

24.5

4) Affiche la dernière valeur

In [15]:
# derniere valeur
print(temperatures.iloc[-1])

27.0

5) Création, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h

In [16]:
# 1 façon : passer directement le paramètre index à la création
temperatures_horaires_v1 = pd.Series(
    [24.5, 25.1, 26.3, 27.0],
    index=["12h", "13h", "14h", "15h"]
)
print("Version 1 (paramètre index) :")
print(temperatures_horaires_v1)

Version 1 (paramètre index) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [17]:
# 2 façon : passer un dictionnaire, dont les clés deviennent l'index
temperatures_horaires_v2 = pd.Series(
    {"12h": 24.5, "13h": 25.1, "14h": 26.3, "15h": 27.0}
)
print("Version 2 (dictionnaire) :")
print(temperatures_horaires_v2)

Version 2 (dictionnaire) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

6) Affiche la 1ère et la dernière valeur

In [19]:
# La 1er et la dernière valeur
print("La premiere valeur est :", temperatures_horaires_v1.iloc[0], 
      "\n la dernier valeur est :", temperatures_horaires_v1.iloc[-1])

La premiere valeur est : 24.5
 la dernier valeur est : 27.0

## Partie 2 – DataFrame

1) Création et affichage du dataframe df_test à partir du dictionnaire suivant 
- data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
}

In [21]:
# dictionnaire
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

# dataframe df_test
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [22]:
# importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

3) Affichage des dimensions de df

In [23]:
# Les dimensions df
print("Dimensions de df (lignes, colonnes) :", df.shape)

Dimensions de df (lignes, colonnes) : (605, 9)