## **Atelier Pandas**

In [ ]:
# Import des bibliothèques nécessaires pour tout le notebook
import pandas as pd
import numpy as np

# On fi
# xe une graine aléatoire globale pour la reproductibilité de l'ensemble du notebook
np.random.seed(42)

print("Pandas version :", pd.__version__)
print("NumPy version  :", np.__version__)

Pandas version : 3.0.5
NumPy version  : 2.5.2

## Partie 1 – Series

1) Création d'une Series contenant 4 températures

In [9]:
# Une Series contenant 4 températures 
temperatures = pd.Series([24.5, 25.1, 26.3, 27.0])
print(temperatures)

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

2) Affichage de l'index

In [10]:
# L'Index
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

3) Affiche la 1ère valeur

In [14]:
# 1er valeur
print(temperatures.iloc[0])

24.5

4) Affiche la dernière valeur

In [15]:
# derniere valeur
print(temperatures.iloc[-1])

27.0

5) Création, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h

In [16]:
# 1 façon : passer directement le paramètre index à la création
temperatures_horaires_v1 = pd.Series(
    [24.5, 25.1, 26.3, 27.0],
    index=["12h", "13h", "14h", "15h"]
)
print("Version 1 (paramètre index) :")
print(temperatures_horaires_v1)

Version 1 (paramètre index) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [17]:
# 2 façon : passer un dictionnaire, dont les clés deviennent l'index
temperatures_horaires_v2 = pd.Series(
    {"12h": 24.5, "13h": 25.1, "14h": 26.3, "15h": 27.0}
)
print("Version 2 (dictionnaire) :")
print(temperatures_horaires_v2)

Version 2 (dictionnaire) :
12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

6) Affiche la 1ère et la dernière valeur

In [19]:
# La 1er et la dernière valeur
print("La premiere valeur est :", temperatures_horaires_v1.iloc[0], 
      "\n la dernier valeur est :", temperatures_horaires_v1.iloc[-1])

La premiere valeur est : 24.5
 la dernier valeur est : 27.0

## Partie 2 – DataFrame

1) Création et affichage du dataframe df_test à partir du dictionnaire suivant 
- data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
}

In [21]:
# dictionnaire
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

# dataframe df_test
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [22]:
# importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

3) Affichage des dimensions de df

In [23]:
# Les dimensions df
print("Dimensions de df (lignes, colonnes) :", df.shape)

Dimensions de df (lignes, colonnes) : (605, 9)

## Partie 3 – Exploration

1) Affichage des premières lignes

In [24]:
# Les 1 lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2) Affichage des 10 premières lignes

In [25]:
# les 10 premières lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3) Affichage des dernières lignes

In [26]:
# Les dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4) Affiche le nombre de lignes

In [31]:
# Nombre de lignes
print("nombre de ligne est :", df.shape[0])

nombre de ligne est : 605

5) Affiche le nombre de colonnes

In [34]:
# Nombre de colonnes 
print("nombre de colonne est :", df.shape[1])

nombre de colonne est : 9

6) Affiche les noms des colonnes

In [35]:
# noms des colonnes
print(df.columns.tolist())

['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

7) Affiche les informations générales

In [36]:
# Les informations generales
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

8) Affiche les statistiques descriptives

In [38]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection

1) Sélection de la colonne "temperature"

In [39]:
# Selection de la colonne tmp
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

2) Sélection des colonnes "temperature", "humidite", "pression" et "consommation"

In [40]:
# Sélection des colonnes "temperature", "humidite", "pression" et "consommation"  
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

3) Sélection des 5 premières lignes avec loc

In [41]:
# les 5 premieres lignes 
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

4) Sélection des 5 premières lignes et les 4 premières colonnes avec iloc

In [42]:
# les 5 premieres lignes et les 4 premiere colonnes
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes

1) Ajoute de la colonne "temperature_fahrenheit"

In [43]:
# ajoute de la colonne
df["temperature_fahrenheit"] = df["temperature"] * 9 / 5 + 32
df[["temperature", "temperature_fahrenheit"]].head()

   temperature  temperature_fahrenheit
0        25.46                  77.828
1        24.00                  75.200
2        25.82                  78.476
3        28.23                  82.814
4        20.58                  69.044

2) Ajoutons la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" 
- (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [44]:
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df[["temperature", "niveau_temperature"]].head()

   temperature niveau_temperature
0        25.46            Normale
1        24.00            Normale
2        25.82            Normale
3        28.23            Normale
4        20.58            Normale

In [45]:
df["niveau_temperature"].value_counts()

niveau_temperature
Normale    559
Élevée      46
Name: count, dtype: int64

3) Renommage de la colonne "humidite" en "humidite_relative"

In [47]:
# renommage de la colonne 
df = df.rename(columns={"humidite": "humidite_relative"})
df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite_relative',
 'pression',
 'consommation',
 'etat',
 'temperature_fahrenheit',
 'niveau_temperature']

4) Supprime de la colonne "temperature_fahrenheit"

In [48]:
# colonne supprimer et nouveau visualisation
df = df.drop(columns=["temperature_fahrenheit"])
df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite_relative',
 'pression',
 'consommation',
 'etat',
 'niveau_temperature']